apiVersion: v1
kind: Service
metadata:
#  creationTimestamp: "2019-09-22T00:47:04Z"
  labels:
{{ include "whiteboard.labels" . | indent 4 }}
  name: {{ include "whiteboard.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    run: {{ include "whiteboard.fullname" . }}

